version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"  # Пробрасываем порт для внешнего доступа
    volumes:
      - ./backend/data:/app/data
    environment:
      - GIN_MODE=release

  frontend:
    build: ./frontend
    ports:
      - "7000:80"    # Пробрасываем порт для внешнего доступа
    depends_on:
      - backend